name: Backport

on:
  push:
    branches:
      - master

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get Time
        id: time
        uses: nanzm/get-time-action@master
        with:
          timeZone: UTC+8
          format: 'YYYY-MM-DD-HH-mm'

      - name: Create commit - Dev
        run: |
          git checkout -b backport/${{ steps.time.outputs.time }}_master-to-develop

      - name: Create Pull Request - Develop
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Backport${{ steps.time.outputs.time }}
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: backport/${{ steps.time.outputs.time }}_master-to-develop
          delete-branch: true
          title: 'Backport ${{ steps.time.outputs.time }} master -> develop'
          draft: true
